"""launch gates

Revision ID: 20ae83a7c377
Revises: b047a8d8496b
Create Date: 2026-09-29 15:47:47.267541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ae83a7c377'
down_revision: Union[str, Sequence[str], None] = 'b047a8d8496b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_gates',
    sa.Column('gate', sa.String(length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=320), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('gate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launch_gates')
    # ### end Alembic commands ###
