"""launch waitlist

Revision ID: 65468d2736c7
Revises: 60dd2afd0c04
Create Date: 2026-09-29 14:10:50.765638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65468d2736c7'
down_revision: Union[str, Sequence[str], None] = '60dd2afd0c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_signups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'product_id', name='waitlist_email_product')
    )
    with op.batch_alter_table('waitlist_signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_signups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_signups_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_signups_email'))
        batch_op.drop_index(batch_op.f('ix_waitlist_signups_created_at'))

    op.drop_table('waitlist_signups')
    # ### end Alembic commands ###
