"""campaign tracking and ad spend

Revision ID: 6d4e039d6301
Revises: d7b10de4af22
Create Date: 2026-09-29 15:23:11.532882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4e039d6301'
down_revision: Union[str, Sequence[str], None] = 'd7b10de4af22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_spend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign', sa.String(length=130), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spend', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('spend >= 0 AND clicks >= 0 AND impressions >= 0', name='ad_spend_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_spend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_spend_campaign'), ['campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_spend_day'), ['day'], unique=False)

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign', sa.String(length=130), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign', sa.String(length=130), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_campaign'), ['campaign'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_campaign'))
        batch_op.drop_column('campaign')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_column('campaign')

    with op.batch_alter_table('ad_spend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_spend_day'))
        batch_op.drop_index(batch_op.f('ix_ad_spend_campaign'))

    op.drop_table('ad_spend')
    # ### end Alembic commands ###
