"""email: marketing consents and messages

Revision ID: 932a75fb0107
Revises: e189569651a6
Create Date: 2026-09-29 15:00:46.900127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932a75fb0107'
down_revision: Union[str, Sequence[str], None] = 'e189569651a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('flow', sa.String(length=32), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('send_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_flow'), ['flow'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_send_after'), ['send_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_to_email'), ['to_email'], unique=False)

    op.create_table('marketing_consents',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketing_consents')
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_messages_to_email'))
        batch_op.drop_index(batch_op.f('ix_email_messages_status'))
        batch_op.drop_index(batch_op.f('ix_email_messages_send_after'))
        batch_op.drop_index(batch_op.f('ix_email_messages_flow'))

    op.drop_table('email_messages')
    # ### end Alembic commands ###
