"""order stock_reserved flag and job leases

Revision ID: ac3fabcd62ba
Revises: 65468d2736c7
Create Date: 2026-09-29 14:25:42.987105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3fabcd62ba'
down_revision: Union[str, Sequence[str], None] = '65468d2736c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_leases',
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_reserved', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))

    # ### end Alembic commands ###
    # Existing data: cancelled orders already gave their stock back. For payment_review
    # we can't tell, so mark them as not holding stock (the safe direction: accepting
    # one later re-reserves stock instead of risking a double release).
    op.execute("UPDATE orders SET stock_reserved = false WHERE status IN ('cancelled', 'payment_review')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('stock_reserved')

    op.drop_table('job_leases')
    # ### end Alembic commands ###
