"""ai tasks, calls, memory, decisions

Revision ID: b047a8d8496b
Revises: e713653201be
Create Date: 2026-09-29 15:35:12.687560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b047a8d8496b'
down_revision: Union[str, Sequence[str], None] = 'e713653201be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_memory',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ai_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('decided_by', sa.String(length=320), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tasks_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tasks_status'), ['status'], unique=False)

    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_chars', sa.Integer(), nullable=False),
    sa.Column('output_chars', sa.Integer(), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ai_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_calls_created_at'), ['created_at'], unique=False)

    op.create_table('business_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('ai_task_id', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_task_id'], ['ai_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_decisions')
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_calls_created_at'))

    op.drop_table('ai_calls')
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_ai_tasks_agent'))

    op.drop_table('ai_tasks')
    op.drop_table('ai_memory')
    # ### end Alembic commands ###
