"""verified purchase reviews

Revision ID: d7b10de4af22
Revises: 932a75fb0107
Create Date: 2026-09-29 15:11:56.377776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b10de4af22'
down_revision: Union[str, Sequence[str], None] = '932a75fb0107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reject_reason', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='rating_1_to_5'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='one_review_per_order_product')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_order_id'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
