"""dropshipping: product supplier fields, supplier orders

Revision ID: e189569651a6
Revises: ac3fabcd62ba
Create Date: 2026-09-29 14:38:17.857163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e189569651a6'
down_revision: Union[str, Sequence[str], None] = 'ac3fabcd62ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_url', sa.String(length=1000), nullable=False),
    sa.Column('supplier_cost_total', sa.Integer(), nullable=False),
    sa.Column('sale_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supplier_ref', sa.String(length=200), nullable=False),
    sa.Column('tracking', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='supplier_order_line')
    )
    with op.batch_alter_table('supplier_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_orders_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_orders_status'), ['status'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_stock', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfilment', sa.String(length=10), server_default='stock', nullable=False))
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=200), server_default='', nullable=False))
        batch_op.add_column(sa.Column('supplier_url', sa.String(length=1000), server_default='', nullable=False))
        batch_op.add_column(sa.Column('supplier_cost', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('delivery_estimate', sa.String(length=100), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('delivery_estimate')
        batch_op.drop_column('supplier_cost')
        batch_op.drop_column('supplier_url')
        batch_op.drop_column('supplier_name')
        batch_op.drop_column('fulfilment')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('from_stock')

    with op.batch_alter_table('supplier_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_orders_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_orders_order_id'))

    op.drop_table('supplier_orders')
    # ### end Alembic commands ###
